<?php
/**
 * NgoApi
 * PHP version 7.3
 *
 * @category Class
 * @package  com.brand4impact.client.invoker
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Total API Reference
 *
 * Este contrato se usara para generar los clientes con todos los servicios necesarios.  `!Uso exclusivo interno!`               ---
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@brand4impact.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace com.brand4impact.client.invoker\com.brand4impact.client.api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use com.brand4impact.client.invoker\ApiException;
use com.brand4impact.client.invoker\Configuration;
use com.brand4impact.client.invoker\HeaderSelector;
use com.brand4impact.client.invoker\ObjectSerializer;

/**
 * NgoApi Class Doc Comment
 *
 * @category Class
 * @package  com.brand4impact.client.invoker
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class NgoApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation createNgo
     *
     * Create a new NGO
     *
     * @param  \com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformNgoCreate $ngo ngo (required)
     * @param  \com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformNgoCreateLegal $legal legal (required)
     * @param  \com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformNgoCreateAdmin $admin admin (required)
     *
     * @throws \com.brand4impact.client.invoker\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \com.brand4impact.client.invoker\com.brand4impact.client.model\RestError|\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError|\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError|\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError|\com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformNgo
     */
    public function createNgo($ngo, $legal, $admin)
    {
        list($response) = $this->createNgoWithHttpInfo($ngo, $legal, $admin);
        return $response;
    }

    /**
     * Operation createNgoWithHttpInfo
     *
     * Create a new NGO
     *
     * @param  \com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformNgoCreate $ngo (required)
     * @param  \com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformNgoCreateLegal $legal (required)
     * @param  \com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformNgoCreateAdmin $admin (required)
     *
     * @throws \com.brand4impact.client.invoker\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \com.brand4impact.client.invoker\com.brand4impact.client.model\RestError|\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError|\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError|\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError|\com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformNgo, HTTP status code, HTTP response headers (array of strings)
     */
    public function createNgoWithHttpInfo($ngo, $legal, $admin)
    {
        $request = $this->createNgoRequest($ngo, $legal, $admin);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 500:
                    if ('\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 403:
                    if ('\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 409:
                    if ('\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 401:
                    if ('\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 201:
                    if ('\com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformNgo' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformNgo', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformNgo';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 409:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformNgo',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation createNgoAsync
     *
     * Create a new NGO
     *
     * @param  \com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformNgoCreate $ngo (required)
     * @param  \com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformNgoCreateLegal $legal (required)
     * @param  \com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformNgoCreateAdmin $admin (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createNgoAsync($ngo, $legal, $admin)
    {
        return $this->createNgoAsyncWithHttpInfo($ngo, $legal, $admin)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation createNgoAsyncWithHttpInfo
     *
     * Create a new NGO
     *
     * @param  \com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformNgoCreate $ngo (required)
     * @param  \com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformNgoCreateLegal $legal (required)
     * @param  \com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformNgoCreateAdmin $admin (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createNgoAsyncWithHttpInfo($ngo, $legal, $admin)
    {
        $returnType = '\com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformNgo';
        $request = $this->createNgoRequest($ngo, $legal, $admin);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'createNgo'
     *
     * @param  \com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformNgoCreate $ngo (required)
     * @param  \com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformNgoCreateLegal $legal (required)
     * @param  \com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformNgoCreateAdmin $admin (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function createNgoRequest($ngo, $legal, $admin)
    {
        // verify the required parameter 'ngo' is set
        if ($ngo === null || (is_array($ngo) && count($ngo) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $ngo when calling createNgo'
            );
        }
        // verify the required parameter 'legal' is set
        if ($legal === null || (is_array($legal) && count($legal) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $legal when calling createNgo'
            );
        }
        // verify the required parameter 'admin' is set
        if ($admin === null || (is_array($admin) && count($admin) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $admin when calling createNgo'
            );
        }

        $resourcePath = '/rest/platform/ngo';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;




        // form params
        if ($ngo !== null) {
            $formParams['ngo'] = ObjectSerializer::toFormValue($ngo);
        }
        // form params
        if ($legal !== null) {
            $formParams['legal'] = ObjectSerializer::toFormValue($legal);
        }
        // form params
        if ($admin !== null) {
            $formParams['admin'] = ObjectSerializer::toFormValue($admin);
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['multipart/form-data']
            );
        }

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getNgo
     *
     * Get your NGO
     *
     *
     * @throws \com.brand4impact.client.invoker\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \com.brand4impact.client.invoker\com.brand4impact.client.model\RestError|\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError|\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError|\com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformNgo|\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError
     */
    public function getNgo()
    {
        list($response) = $this->getNgoWithHttpInfo();
        return $response;
    }

    /**
     * Operation getNgoWithHttpInfo
     *
     * Get your NGO
     *
     *
     * @throws \com.brand4impact.client.invoker\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \com.brand4impact.client.invoker\com.brand4impact.client.model\RestError|\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError|\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError|\com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformNgo|\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError, HTTP status code, HTTP response headers (array of strings)
     */
    public function getNgoWithHttpInfo()
    {
        $request = $this->getNgoRequest();

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 500:
                    if ('\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 403:
                    if ('\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 409:
                    if ('\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 200:
                    if ('\com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformNgo' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformNgo', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 401:
                    if ('\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformNgo';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 409:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformNgo',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getNgoAsync
     *
     * Get your NGO
     *
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getNgoAsync()
    {
        return $this->getNgoAsyncWithHttpInfo()
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getNgoAsyncWithHttpInfo
     *
     * Get your NGO
     *
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getNgoAsyncWithHttpInfo()
    {
        $returnType = '\com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformNgo';
        $request = $this->getNgoRequest();

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getNgo'
     *
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getNgoRequest()
    {

        $resourcePath = '/rest/platform/ngo';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation updateNgo
     *
     * Update NGO data
     *
     * @param  \com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformNgoUpdate $ngo ngo (required)
     * @param  \SplFileObject $logo logo (required)
     *
     * @throws \com.brand4impact.client.invoker\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \com.brand4impact.client.invoker\com.brand4impact.client.model\RestError|\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError|\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError|\com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformNgo|\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError
     */
    public function updateNgo($ngo, $logo)
    {
        list($response) = $this->updateNgoWithHttpInfo($ngo, $logo);
        return $response;
    }

    /**
     * Operation updateNgoWithHttpInfo
     *
     * Update NGO data
     *
     * @param  \com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformNgoUpdate $ngo (required)
     * @param  \SplFileObject $logo (required)
     *
     * @throws \com.brand4impact.client.invoker\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \com.brand4impact.client.invoker\com.brand4impact.client.model\RestError|\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError|\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError|\com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformNgo|\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError, HTTP status code, HTTP response headers (array of strings)
     */
    public function updateNgoWithHttpInfo($ngo, $logo)
    {
        $request = $this->updateNgoRequest($ngo, $logo);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 500:
                    if ('\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 403:
                    if ('\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 409:
                    if ('\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 200:
                    if ('\com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformNgo' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformNgo', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 401:
                    if ('\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformNgo';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 409:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformNgo',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation updateNgoAsync
     *
     * Update NGO data
     *
     * @param  \com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformNgoUpdate $ngo (required)
     * @param  \SplFileObject $logo (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateNgoAsync($ngo, $logo)
    {
        return $this->updateNgoAsyncWithHttpInfo($ngo, $logo)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation updateNgoAsyncWithHttpInfo
     *
     * Update NGO data
     *
     * @param  \com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformNgoUpdate $ngo (required)
     * @param  \SplFileObject $logo (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateNgoAsyncWithHttpInfo($ngo, $logo)
    {
        $returnType = '\com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformNgo';
        $request = $this->updateNgoRequest($ngo, $logo);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'updateNgo'
     *
     * @param  \com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformNgoUpdate $ngo (required)
     * @param  \SplFileObject $logo (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function updateNgoRequest($ngo, $logo)
    {
        // verify the required parameter 'ngo' is set
        if ($ngo === null || (is_array($ngo) && count($ngo) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $ngo when calling updateNgo'
            );
        }
        // verify the required parameter 'logo' is set
        if ($logo === null || (is_array($logo) && count($logo) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $logo when calling updateNgo'
            );
        }

        $resourcePath = '/rest/platform/ngo';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;




        // form params
        if ($ngo !== null) {
            $formParams['ngo'] = ObjectSerializer::toFormValue($ngo);
        }
        // form params
        if ($logo !== null) {
            $multipart = true;
            $formParams['logo'] = [];
            $paramFiles = is_array($logo) ? $logo : [$logo];
            foreach ($paramFiles as $paramFile) {
                $formParams['logo'][] = \GuzzleHttp\Psr7\Utils::tryFopen(
                    ObjectSerializer::toFormValue($paramFile),
                    'rb'
                );
            }
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['multipart/form-data']
            );
        }

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'PUT',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation updateNgoBank
     *
     * Update bank NGO info
     *
     * @param  \com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformNgoUpdateBank $bank bank (required)
     *
     * @throws \com.brand4impact.client.invoker\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformNgo|\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError|\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError|\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError|\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError
     */
    public function updateNgoBank($bank)
    {
        list($response) = $this->updateNgoBankWithHttpInfo($bank);
        return $response;
    }

    /**
     * Operation updateNgoBankWithHttpInfo
     *
     * Update bank NGO info
     *
     * @param  \com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformNgoUpdateBank $bank (required)
     *
     * @throws \com.brand4impact.client.invoker\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformNgo|\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError|\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError|\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError|\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError, HTTP status code, HTTP response headers (array of strings)
     */
    public function updateNgoBankWithHttpInfo($bank)
    {
        $request = $this->updateNgoBankRequest($bank);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformNgo' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformNgo', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 500:
                    if ('\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 403:
                    if ('\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 409:
                    if ('\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 401:
                    if ('\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformNgo';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformNgo',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 409:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation updateNgoBankAsync
     *
     * Update bank NGO info
     *
     * @param  \com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformNgoUpdateBank $bank (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateNgoBankAsync($bank)
    {
        return $this->updateNgoBankAsyncWithHttpInfo($bank)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation updateNgoBankAsyncWithHttpInfo
     *
     * Update bank NGO info
     *
     * @param  \com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformNgoUpdateBank $bank (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateNgoBankAsyncWithHttpInfo($bank)
    {
        $returnType = '\com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformNgo';
        $request = $this->updateNgoBankRequest($bank);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'updateNgoBank'
     *
     * @param  \com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformNgoUpdateBank $bank (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function updateNgoBankRequest($bank)
    {
        // verify the required parameter 'bank' is set
        if ($bank === null || (is_array($bank) && count($bank) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $bank when calling updateNgoBank'
            );
        }

        $resourcePath = '/rest/platform/ngo/bank';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;




        // form params
        if ($bank !== null) {
            $formParams['bank'] = ObjectSerializer::toFormValue($bank);
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['multipart/form-data']
            );
        }

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'PUT',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation updateNgoLegal
     *
     * Update legal NGO info
     *
     * @param  \com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformNgoUpdateLegal $legal legal (required)
     *
     * @throws \com.brand4impact.client.invoker\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \com.brand4impact.client.invoker\com.brand4impact.client.model\RestError|\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError|\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError|\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError|\com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformNgo
     */
    public function updateNgoLegal($legal)
    {
        list($response) = $this->updateNgoLegalWithHttpInfo($legal);
        return $response;
    }

    /**
     * Operation updateNgoLegalWithHttpInfo
     *
     * Update legal NGO info
     *
     * @param  \com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformNgoUpdateLegal $legal (required)
     *
     * @throws \com.brand4impact.client.invoker\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \com.brand4impact.client.invoker\com.brand4impact.client.model\RestError|\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError|\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError|\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError|\com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformNgo, HTTP status code, HTTP response headers (array of strings)
     */
    public function updateNgoLegalWithHttpInfo($legal)
    {
        $request = $this->updateNgoLegalRequest($legal);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 500:
                    if ('\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 403:
                    if ('\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 409:
                    if ('\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 401:
                    if ('\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 200:
                    if ('\com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformNgo' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformNgo', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformNgo';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 409:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformNgo',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation updateNgoLegalAsync
     *
     * Update legal NGO info
     *
     * @param  \com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformNgoUpdateLegal $legal (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateNgoLegalAsync($legal)
    {
        return $this->updateNgoLegalAsyncWithHttpInfo($legal)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation updateNgoLegalAsyncWithHttpInfo
     *
     * Update legal NGO info
     *
     * @param  \com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformNgoUpdateLegal $legal (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateNgoLegalAsyncWithHttpInfo($legal)
    {
        $returnType = '\com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformNgo';
        $request = $this->updateNgoLegalRequest($legal);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'updateNgoLegal'
     *
     * @param  \com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformNgoUpdateLegal $legal (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function updateNgoLegalRequest($legal)
    {
        // verify the required parameter 'legal' is set
        if ($legal === null || (is_array($legal) && count($legal) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $legal when calling updateNgoLegal'
            );
        }

        $resourcePath = '/rest/platform/ngo/legal';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;




        // form params
        if ($legal !== null) {
            $formParams['legal'] = ObjectSerializer::toFormValue($legal);
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['multipart/form-data']
            );
        }

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'PUT',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation uploadNgoFiles
     *
     * Upload NGO files
     *
     * @param  \SplFileObject $file file (required)
     *
     * @throws \com.brand4impact.client.invoker\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformNgo|\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError|\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError|\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError|\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError
     */
    public function uploadNgoFiles($file)
    {
        list($response) = $this->uploadNgoFilesWithHttpInfo($file);
        return $response;
    }

    /**
     * Operation uploadNgoFilesWithHttpInfo
     *
     * Upload NGO files
     *
     * @param  \SplFileObject $file (required)
     *
     * @throws \com.brand4impact.client.invoker\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformNgo|\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError|\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError|\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError|\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError, HTTP status code, HTTP response headers (array of strings)
     */
    public function uploadNgoFilesWithHttpInfo($file)
    {
        $request = $this->uploadNgoFilesRequest($file);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformNgo' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformNgo', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 500:
                    if ('\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 403:
                    if ('\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 409:
                    if ('\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 401:
                    if ('\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformNgo';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformNgo',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 409:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation uploadNgoFilesAsync
     *
     * Upload NGO files
     *
     * @param  \SplFileObject $file (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function uploadNgoFilesAsync($file)
    {
        return $this->uploadNgoFilesAsyncWithHttpInfo($file)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation uploadNgoFilesAsyncWithHttpInfo
     *
     * Upload NGO files
     *
     * @param  \SplFileObject $file (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function uploadNgoFilesAsyncWithHttpInfo($file)
    {
        $returnType = '\com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformNgo';
        $request = $this->uploadNgoFilesRequest($file);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'uploadNgoFiles'
     *
     * @param  \SplFileObject $file (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function uploadNgoFilesRequest($file)
    {
        // verify the required parameter 'file' is set
        if ($file === null || (is_array($file) && count($file) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $file when calling uploadNgoFiles'
            );
        }

        $resourcePath = '/rest/platform/ngo/upload';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;




        // form params
        if ($file !== null) {
            $multipart = true;
            $formParams['file'] = [];
            $paramFiles = is_array($file) ? $file : [$file];
            foreach ($paramFiles as $paramFile) {
                $formParams['file'][] = \GuzzleHttp\Psr7\Utils::tryFopen(
                    ObjectSerializer::toFormValue($paramFile),
                    'rb'
                );
            }
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['multipart/form-data']
            );
        }

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'PUT',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
