<?php
/**
 * ProjectApi
 * PHP version 7.3
 *
 * @category Class
 * @package  com.brand4impact.client.invoker
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Total API Reference
 *
 * Este contrato se usara para generar los clientes con todos los servicios necesarios.  `!Uso exclusivo interno!`               ---
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@brand4impact.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace com.brand4impact.client.invoker\com.brand4impact.client.api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use com.brand4impact.client.invoker\ApiException;
use com.brand4impact.client.invoker\Configuration;
use com.brand4impact.client.invoker\HeaderSelector;
use com.brand4impact.client.invoker\ObjectSerializer;

/**
 * ProjectApi Class Doc Comment
 *
 * @category Class
 * @package  com.brand4impact.client.invoker
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ProjectApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation createProject
     *
     * Create a new project
     *
     * @param  \com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformProjectCreate $project project (required)
     * @param  \SplFileObject $primaryImage primaryImage (required)
     * @param  \SplFileObject $secondaryImage secondaryImage (required)
     *
     * @throws \com.brand4impact.client.invoker\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \com.brand4impact.client.invoker\com.brand4impact.client.model\RestError|\com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformProject|\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError|\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError|\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError
     */
    public function createProject($project, $primaryImage, $secondaryImage)
    {
        list($response) = $this->createProjectWithHttpInfo($project, $primaryImage, $secondaryImage);
        return $response;
    }

    /**
     * Operation createProjectWithHttpInfo
     *
     * Create a new project
     *
     * @param  \com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformProjectCreate $project (required)
     * @param  \SplFileObject $primaryImage (required)
     * @param  \SplFileObject $secondaryImage (required)
     *
     * @throws \com.brand4impact.client.invoker\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \com.brand4impact.client.invoker\com.brand4impact.client.model\RestError|\com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformProject|\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError|\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError|\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError, HTTP status code, HTTP response headers (array of strings)
     */
    public function createProjectWithHttpInfo($project, $primaryImage, $secondaryImage)
    {
        $request = $this->createProjectRequest($project, $primaryImage, $secondaryImage);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 500:
                    if ('\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 201:
                    if ('\com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformProject' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformProject', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 403:
                    if ('\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 409:
                    if ('\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 401:
                    if ('\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformProject';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformProject',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 409:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation createProjectAsync
     *
     * Create a new project
     *
     * @param  \com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformProjectCreate $project (required)
     * @param  \SplFileObject $primaryImage (required)
     * @param  \SplFileObject $secondaryImage (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createProjectAsync($project, $primaryImage, $secondaryImage)
    {
        return $this->createProjectAsyncWithHttpInfo($project, $primaryImage, $secondaryImage)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation createProjectAsyncWithHttpInfo
     *
     * Create a new project
     *
     * @param  \com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformProjectCreate $project (required)
     * @param  \SplFileObject $primaryImage (required)
     * @param  \SplFileObject $secondaryImage (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createProjectAsyncWithHttpInfo($project, $primaryImage, $secondaryImage)
    {
        $returnType = '\com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformProject';
        $request = $this->createProjectRequest($project, $primaryImage, $secondaryImage);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'createProject'
     *
     * @param  \com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformProjectCreate $project (required)
     * @param  \SplFileObject $primaryImage (required)
     * @param  \SplFileObject $secondaryImage (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function createProjectRequest($project, $primaryImage, $secondaryImage)
    {
        // verify the required parameter 'project' is set
        if ($project === null || (is_array($project) && count($project) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $project when calling createProject'
            );
        }
        // verify the required parameter 'primaryImage' is set
        if ($primaryImage === null || (is_array($primaryImage) && count($primaryImage) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $primaryImage when calling createProject'
            );
        }
        // verify the required parameter 'secondaryImage' is set
        if ($secondaryImage === null || (is_array($secondaryImage) && count($secondaryImage) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $secondaryImage when calling createProject'
            );
        }

        $resourcePath = '/rest/platform/project';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;




        // form params
        if ($project !== null) {
            $formParams['project'] = ObjectSerializer::toFormValue($project);
        }
        // form params
        if ($primaryImage !== null) {
            $multipart = true;
            $formParams['primaryImage'] = [];
            $paramFiles = is_array($primaryImage) ? $primaryImage : [$primaryImage];
            foreach ($paramFiles as $paramFile) {
                $formParams['primaryImage'][] = \GuzzleHttp\Psr7\Utils::tryFopen(
                    ObjectSerializer::toFormValue($paramFile),
                    'rb'
                );
            }
        }
        // form params
        if ($secondaryImage !== null) {
            $multipart = true;
            $formParams['secondaryImage'] = [];
            $paramFiles = is_array($secondaryImage) ? $secondaryImage : [$secondaryImage];
            foreach ($paramFiles as $paramFile) {
                $formParams['secondaryImage'][] = \GuzzleHttp\Psr7\Utils::tryFopen(
                    ObjectSerializer::toFormValue($paramFile),
                    'rb'
                );
            }
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['multipart/form-data']
            );
        }

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getProject
     *
     * Get a single project
     *
     * @param  string $token The unique token for the campaign. (required)
     *
     * @throws \com.brand4impact.client.invoker\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \com.brand4impact.client.invoker\com.brand4impact.client.model\RestError|\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError|\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError|\com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformProject|\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError
     */
    public function getProject($token)
    {
        list($response) = $this->getProjectWithHttpInfo($token);
        return $response;
    }

    /**
     * Operation getProjectWithHttpInfo
     *
     * Get a single project
     *
     * @param  string $token The unique token for the campaign. (required)
     *
     * @throws \com.brand4impact.client.invoker\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \com.brand4impact.client.invoker\com.brand4impact.client.model\RestError|\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError|\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError|\com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformProject|\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError, HTTP status code, HTTP response headers (array of strings)
     */
    public function getProjectWithHttpInfo($token)
    {
        $request = $this->getProjectRequest($token);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 500:
                    if ('\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 403:
                    if ('\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 409:
                    if ('\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 200:
                    if ('\com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformProject' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformProject', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 401:
                    if ('\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformProject';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 409:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformProject',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getProjectAsync
     *
     * Get a single project
     *
     * @param  string $token The unique token for the campaign. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getProjectAsync($token)
    {
        return $this->getProjectAsyncWithHttpInfo($token)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getProjectAsyncWithHttpInfo
     *
     * Get a single project
     *
     * @param  string $token The unique token for the campaign. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getProjectAsyncWithHttpInfo($token)
    {
        $returnType = '\com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformProject';
        $request = $this->getProjectRequest($token);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getProject'
     *
     * @param  string $token The unique token for the campaign. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getProjectRequest($token)
    {
        // verify the required parameter 'token' is set
        if ($token === null || (is_array($token) && count($token) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $token when calling getProject'
            );
        }

        $resourcePath = '/rest/platform/project/{token}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($token !== null) {
            $resourcePath = str_replace(
                '{' . 'token' . '}',
                ObjectSerializer::toPathValue($token),
                $resourcePath
            );
        }


        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getProjects
     *
     * Get a set of projects
     *
     * @param  string $descriptionLike descriptionLike (optional)
     * @param  string $country The country (optional)
     * @param  string $topicToken The topicToken (optional)
     * @param  int $page The number of the page. Possible values: 0 to unlimited (optional)
     * @param  int $size The number of items inside a page. Possible values: 1 to 100 (optional)
     * @param  string $sort The order direction for sorted results. Possible values: ASC or DESC (optional)
     *
     * @throws \com.brand4impact.client.invoker\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \com.brand4impact.client.invoker\com.brand4impact.client.model\RestError|\com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformProjectItemWrapper|\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError|\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError|\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError
     */
    public function getProjects($descriptionLike = null, $country = null, $topicToken = null, $page = null, $size = null, $sort = null)
    {
        list($response) = $this->getProjectsWithHttpInfo($descriptionLike, $country, $topicToken, $page, $size, $sort);
        return $response;
    }

    /**
     * Operation getProjectsWithHttpInfo
     *
     * Get a set of projects
     *
     * @param  string $descriptionLike (optional)
     * @param  string $country The country (optional)
     * @param  string $topicToken The topicToken (optional)
     * @param  int $page The number of the page. Possible values: 0 to unlimited (optional)
     * @param  int $size The number of items inside a page. Possible values: 1 to 100 (optional)
     * @param  string $sort The order direction for sorted results. Possible values: ASC or DESC (optional)
     *
     * @throws \com.brand4impact.client.invoker\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \com.brand4impact.client.invoker\com.brand4impact.client.model\RestError|\com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformProjectItemWrapper|\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError|\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError|\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError, HTTP status code, HTTP response headers (array of strings)
     */
    public function getProjectsWithHttpInfo($descriptionLike = null, $country = null, $topicToken = null, $page = null, $size = null, $sort = null)
    {
        $request = $this->getProjectsRequest($descriptionLike, $country, $topicToken, $page, $size, $sort);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 500:
                    if ('\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 200:
                    if ('\com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformProjectItemWrapper' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformProjectItemWrapper', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 403:
                    if ('\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 409:
                    if ('\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 401:
                    if ('\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformProjectItemWrapper';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformProjectItemWrapper',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 409:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getProjectsAsync
     *
     * Get a set of projects
     *
     * @param  string $descriptionLike (optional)
     * @param  string $country The country (optional)
     * @param  string $topicToken The topicToken (optional)
     * @param  int $page The number of the page. Possible values: 0 to unlimited (optional)
     * @param  int $size The number of items inside a page. Possible values: 1 to 100 (optional)
     * @param  string $sort The order direction for sorted results. Possible values: ASC or DESC (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getProjectsAsync($descriptionLike = null, $country = null, $topicToken = null, $page = null, $size = null, $sort = null)
    {
        return $this->getProjectsAsyncWithHttpInfo($descriptionLike, $country, $topicToken, $page, $size, $sort)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getProjectsAsyncWithHttpInfo
     *
     * Get a set of projects
     *
     * @param  string $descriptionLike (optional)
     * @param  string $country The country (optional)
     * @param  string $topicToken The topicToken (optional)
     * @param  int $page The number of the page. Possible values: 0 to unlimited (optional)
     * @param  int $size The number of items inside a page. Possible values: 1 to 100 (optional)
     * @param  string $sort The order direction for sorted results. Possible values: ASC or DESC (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getProjectsAsyncWithHttpInfo($descriptionLike = null, $country = null, $topicToken = null, $page = null, $size = null, $sort = null)
    {
        $returnType = '\com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformProjectItemWrapper';
        $request = $this->getProjectsRequest($descriptionLike, $country, $topicToken, $page, $size, $sort);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getProjects'
     *
     * @param  string $descriptionLike (optional)
     * @param  string $country The country (optional)
     * @param  string $topicToken The topicToken (optional)
     * @param  int $page The number of the page. Possible values: 0 to unlimited (optional)
     * @param  int $size The number of items inside a page. Possible values: 1 to 100 (optional)
     * @param  string $sort The order direction for sorted results. Possible values: ASC or DESC (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getProjectsRequest($descriptionLike = null, $country = null, $topicToken = null, $page = null, $size = null, $sort = null)
    {

        $resourcePath = '/rest/platform/project';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($descriptionLike !== null) {
            if('form' === 'form' && is_array($descriptionLike)) {
                foreach($descriptionLike as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['descriptionLike'] = $descriptionLike;
            }
        }
        // query params
        if ($country !== null) {
            if('form' === 'form' && is_array($country)) {
                foreach($country as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['country'] = $country;
            }
        }
        // query params
        if ($topicToken !== null) {
            if('form' === 'form' && is_array($topicToken)) {
                foreach($topicToken as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['topicToken'] = $topicToken;
            }
        }
        // query params
        if ($page !== null) {
            if('form' === 'form' && is_array($page)) {
                foreach($page as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['page'] = $page;
            }
        }
        // query params
        if ($size !== null) {
            if('form' === 'form' && is_array($size)) {
                foreach($size as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['size'] = $size;
            }
        }
        // query params
        if ($sort !== null) {
            if('form' === 'form' && is_array($sort)) {
                foreach($sort as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['sort'] = $sort;
            }
        }




        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation switchProject
     *
     * Switch project status
     *
     * @param  string $token token (required)
     *
     * @throws \com.brand4impact.client.invoker\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \com.brand4impact.client.invoker\com.brand4impact.client.model\RestError|\com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformProject|\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError|\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError|\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError
     */
    public function switchProject($token)
    {
        list($response) = $this->switchProjectWithHttpInfo($token);
        return $response;
    }

    /**
     * Operation switchProjectWithHttpInfo
     *
     * Switch project status
     *
     * @param  string $token (required)
     *
     * @throws \com.brand4impact.client.invoker\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \com.brand4impact.client.invoker\com.brand4impact.client.model\RestError|\com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformProject|\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError|\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError|\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError, HTTP status code, HTTP response headers (array of strings)
     */
    public function switchProjectWithHttpInfo($token)
    {
        $request = $this->switchProjectRequest($token);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 500:
                    if ('\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 200:
                    if ('\com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformProject' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformProject', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 403:
                    if ('\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 409:
                    if ('\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 401:
                    if ('\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformProject';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformProject',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 409:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation switchProjectAsync
     *
     * Switch project status
     *
     * @param  string $token (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function switchProjectAsync($token)
    {
        return $this->switchProjectAsyncWithHttpInfo($token)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation switchProjectAsyncWithHttpInfo
     *
     * Switch project status
     *
     * @param  string $token (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function switchProjectAsyncWithHttpInfo($token)
    {
        $returnType = '\com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformProject';
        $request = $this->switchProjectRequest($token);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'switchProject'
     *
     * @param  string $token (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function switchProjectRequest($token)
    {
        // verify the required parameter 'token' is set
        if ($token === null || (is_array($token) && count($token) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $token when calling switchProject'
            );
        }

        $resourcePath = '/rest/platform/project/{token}/switch';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($token !== null) {
            $resourcePath = str_replace(
                '{' . 'token' . '}',
                ObjectSerializer::toPathValue($token),
                $resourcePath
            );
        }


        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'PUT',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation updateProject
     *
     * Update a project
     *
     * @param  string $token token (required)
     * @param  \com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformProjectUpdate $project project (required)
     * @param  \SplFileObject $primaryImage primaryImage (required)
     * @param  \SplFileObject $secondaryImage secondaryImage (required)
     *
     * @throws \com.brand4impact.client.invoker\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \com.brand4impact.client.invoker\com.brand4impact.client.model\RestError|\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError|\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError|\com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformProject|\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError
     */
    public function updateProject($token, $project, $primaryImage, $secondaryImage)
    {
        list($response) = $this->updateProjectWithHttpInfo($token, $project, $primaryImage, $secondaryImage);
        return $response;
    }

    /**
     * Operation updateProjectWithHttpInfo
     *
     * Update a project
     *
     * @param  string $token (required)
     * @param  \com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformProjectUpdate $project (required)
     * @param  \SplFileObject $primaryImage (required)
     * @param  \SplFileObject $secondaryImage (required)
     *
     * @throws \com.brand4impact.client.invoker\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \com.brand4impact.client.invoker\com.brand4impact.client.model\RestError|\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError|\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError|\com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformProject|\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError, HTTP status code, HTTP response headers (array of strings)
     */
    public function updateProjectWithHttpInfo($token, $project, $primaryImage, $secondaryImage)
    {
        $request = $this->updateProjectRequest($token, $project, $primaryImage, $secondaryImage);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 500:
                    if ('\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 403:
                    if ('\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 409:
                    if ('\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 200:
                    if ('\com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformProject' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformProject', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 401:
                    if ('\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformProject';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 409:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformProject',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\com.brand4impact.client.invoker\com.brand4impact.client.model\RestError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation updateProjectAsync
     *
     * Update a project
     *
     * @param  string $token (required)
     * @param  \com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformProjectUpdate $project (required)
     * @param  \SplFileObject $primaryImage (required)
     * @param  \SplFileObject $secondaryImage (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateProjectAsync($token, $project, $primaryImage, $secondaryImage)
    {
        return $this->updateProjectAsyncWithHttpInfo($token, $project, $primaryImage, $secondaryImage)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation updateProjectAsyncWithHttpInfo
     *
     * Update a project
     *
     * @param  string $token (required)
     * @param  \com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformProjectUpdate $project (required)
     * @param  \SplFileObject $primaryImage (required)
     * @param  \SplFileObject $secondaryImage (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateProjectAsyncWithHttpInfo($token, $project, $primaryImage, $secondaryImage)
    {
        $returnType = '\com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformProject';
        $request = $this->updateProjectRequest($token, $project, $primaryImage, $secondaryImage);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'updateProject'
     *
     * @param  string $token (required)
     * @param  \com.brand4impact.client.invoker\com.brand4impact.client.model\PlatformProjectUpdate $project (required)
     * @param  \SplFileObject $primaryImage (required)
     * @param  \SplFileObject $secondaryImage (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function updateProjectRequest($token, $project, $primaryImage, $secondaryImage)
    {
        // verify the required parameter 'token' is set
        if ($token === null || (is_array($token) && count($token) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $token when calling updateProject'
            );
        }
        // verify the required parameter 'project' is set
        if ($project === null || (is_array($project) && count($project) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $project when calling updateProject'
            );
        }
        // verify the required parameter 'primaryImage' is set
        if ($primaryImage === null || (is_array($primaryImage) && count($primaryImage) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $primaryImage when calling updateProject'
            );
        }
        // verify the required parameter 'secondaryImage' is set
        if ($secondaryImage === null || (is_array($secondaryImage) && count($secondaryImage) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $secondaryImage when calling updateProject'
            );
        }

        $resourcePath = '/rest/platform/project/{token}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($token !== null) {
            $resourcePath = str_replace(
                '{' . 'token' . '}',
                ObjectSerializer::toPathValue($token),
                $resourcePath
            );
        }

        // form params
        if ($project !== null) {
            $formParams['project'] = ObjectSerializer::toFormValue($project);
        }
        // form params
        if ($primaryImage !== null) {
            $multipart = true;
            $formParams['primaryImage'] = [];
            $paramFiles = is_array($primaryImage) ? $primaryImage : [$primaryImage];
            foreach ($paramFiles as $paramFile) {
                $formParams['primaryImage'][] = \GuzzleHttp\Psr7\Utils::tryFopen(
                    ObjectSerializer::toFormValue($paramFile),
                    'rb'
                );
            }
        }
        // form params
        if ($secondaryImage !== null) {
            $multipart = true;
            $formParams['secondaryImage'] = [];
            $paramFiles = is_array($secondaryImage) ? $secondaryImage : [$secondaryImage];
            foreach ($paramFiles as $paramFile) {
                $formParams['secondaryImage'][] = \GuzzleHttp\Psr7\Utils::tryFopen(
                    ObjectSerializer::toFormValue($paramFile),
                    'rb'
                );
            }
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['multipart/form-data']
            );
        }

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'PUT',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
