<?php
/**
 * CompanyApiTest
 * PHP version 7.3
 *
 * @category Class
 * @package  com.brand4impact.client.invoker
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Total API Reference
 *
 * Este contrato se usara para generar los clientes con todos los servicios necesarios.  `!Uso exclusivo interno!`               ---
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@brand4impact.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace com.brand4impact.client.invoker\Test\Api;

use \com.brand4impact.client.invoker\Configuration;
use \com.brand4impact.client.invoker\ApiException;
use \com.brand4impact.client.invoker\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * CompanyApiTest Class Doc Comment
 *
 * @category Class
 * @package  com.brand4impact.client.invoker
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CompanyApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createCompany
     *
     * Create a new Company.
     *
     */
    public function testCreateCompany()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCompany
     *
     * Get your Company.
     *
     */
    public function testGetCompany()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateCompany
     *
     * Update Company data.
     *
     */
    public function testUpdateCompany()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateCompanyLegal
     *
     * Update legal Company info.
     *
     */
    public function testUpdateCompanyLegal()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateCompanyTopic
     *
     * Update selected topics for your Company.
     *
     */
    public function testUpdateCompanyTopic()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
